# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/build-and-push-image"
    schedule:
      interval: "monthly"
    groups:
      build-and-push-image:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci/cd"
      - "github-actions"

    ###Action 2
  - package-ecosystem: "github-actions"
    directory: "/build-and-push-image-aws"
    schedule:
      interval: "monthly"
    groups:
      build-and-push-image-aws:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci/cd"
      - "github-actions"


    ###Action 3
  - package-ecosystem: "github-actions"
    directory: "/build-and-push-python-package"
    schedule:
      interval: "monthly"
    groups:
      python:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci/cd"
      - "github-actions"


    ###Action 4
  - package-ecosystem: "github-actions"
    directory: "/lint-helm-chart-v2"
    schedule:
      interval: "monthly"
    groups:
      lint-helm-chart:
        applies-to: version-updates
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "ci/cd"
      - "github-actions"